# Generated by Django 4.1 on 2023-01-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='std',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=40)),
                ('r', models.IntegerField()),
                ('e', models.CharField(max_length=40)),
                ('d', models.CharField(max_length=40)),
            ],
        ),
    ]
