# Generated by Django 4.1.1 on 2022-08-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('pas', models.CharField(max_length=12)),
            ],
        ),
    ]
