# Generated by Django 4.1.1 on 2022-09-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('uname', models.CharField(max_length=122, primary_key=True, serialize=False)),
                ('pas', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=122)),
            ],
        ),
    ]
