# Generated by Django 4.1 on 2022-10-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesinfo',
            name='image',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='moviesinfo',
            name='release_year',
            field=models.CharField(max_length=122),
        ),
    ]
