# Generated by Django 4.1 on 2022-10-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_moviesinfo_image_alter_moviesinfo_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesinfo',
            name='release_year',
            field=models.TextField(),
        ),
    ]
