# Generated by Django 4.1 on 2022-10-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_moviesinfo_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesinfo',
            name='image',
            field=models.TextField(),
        ),
    ]
