# Generated by Django 4.1 on 2022-10-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='book_avail',
            field=models.CharField(choices=[('avail', 'available'), ('unavail', 'unavailable')], default='unavailable', max_length=20),
        ),
    ]
