# Generated by Django 4.1 on 2022-10-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_view', '0004_alter_library_book_avail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='book_avail',
            field=models.CharField(max_length=200),
        ),
    ]
