# Generated by Django 4.1 on 2022-10-04 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logs',
        ),
    ]
