# Generated by Django 3.1.5 on 2023-01-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
