# Generated by Django 3.2 on 2023-01-11 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_staff_station_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.BooleanField(default=True)),
                ('inFlow', models.CharField(max_length=100)),
                ('completed', models.CharField(max_length=100)),
                ('recall', models.CharField(max_length=100)),
                ('cancelled', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('delay', models.CharField(max_length=100)),
                ('staffId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.staff')),
            ],
        ),
    ]
