# Generated by Django 3.2 on 2023-01-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='delay',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='inFlow',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='cancel',
            field=models.CharField(default=4281216584, max_length=100),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='complete',
            field=models.CharField(default=4281216584, max_length=100),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='cooking',
            field=models.CharField(default=4281216584, max_length=100),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='dragged',
            field=models.CharField(default=4281216584, max_length=100),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='incoming',
            field=models.CharField(default=4281216584, max_length=100),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='nearTo',
            field=models.CharField(default=4281216584, max_length=100),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='priority',
            field=models.CharField(default=4281216584, max_length=100),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='recall',
            field=models.CharField(default=4281216584, max_length=100),
        ),
    ]
