# Generated by Django 3.2 on 2023-01-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20230111_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='isStation',
            field=models.BooleanField(default=True),
        ),
    ]
