# Generated by Django 3.2 on 2023-01-13 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_stations_isstation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='staffId',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='stationId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='service.stations'),
        ),
    ]
