# Generated by Django 3.2 on 2023-01-13 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20230113_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='stationId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.stations'),
        ),
    ]
