# Generated by Django 3.2 on 2023-01-13 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_usersettings_stationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='stationId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.stations', unique=True),
        ),
    ]
