# Generated by Django 3.2 on 2023-01-13 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_preparationtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_content',
            name='stationId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.stations'),
            preserve_default=False,
        ),
    ]
