# Generated by Django 3.2 on 2023-01-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20230113_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arrival_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
