# Generated by Django 4.0.3 on 2023-01-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_order_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arrival_time',
            field=models.CharField(max_length=90),
        ),
    ]
