# Generated by Django 4.0.3 on 2023-01-19 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_alter_order_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.order_point'),
        ),
    ]
